### ISSUE TITLE
Complete the guide

### ISSUE THREAD

**Issue by alixedi** [alixedi/pyconuk-2018-k8s#19]
The guide should allow anyone to go through the workshop on their own. 

This means it should include *everything*. Things we are speaking (e.g. k8s architecture overview), things we are typing (e.g. curl).

**Comment by pvanderlinden** [comment]
- cluster vs machines, pets vs cattle
- for all assignments: have relevant info (example dockerfile, commands, etc) on one slide/guide

**Comment by pvanderlinden** [comment]
explain: a service works like watch (in our last example)
